# Generated by Django 4.1.7 on 2023-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Diabetes', models.CharField(max_length=10)),
                ('BloodPressureProblems', models.CharField(max_length=10)),
                ('Transplants', models.CharField(max_length=10)),
                ('ChronicDiseases', models.CharField(max_length=10)),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Allergies', models.CharField(max_length=10)),
                ('HistoryOfCancerInFamily', models.CharField(max_length=10)),
                ('NumberOfMajorSurgeries', models.IntegerField()),
                ('Premium', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
